export const PRESET_SCENARIOS = [
  {
    id: "yaz-indirim",
    name: "Yaz İndirim Kampanyası",
    icon: "🌞",
    module: "campaign",
    description: "Yaz sezonu klasik %25 indirim simülasyonu",
    inputs: { campaignType: "discount", discountPct: 0.25, demandLift: 0.50 },
  },
  {
    id: "bayram-ucretsiz-kargo",
    name: "Bayram Ücretsiz Kargo",
    icon: "🎁",
    module: "campaign",
    description: "Bayram döneminde ücretsiz kargo etkisi",
    inputs: { campaignType: "freeShipping", demandLift: 0.40 },
  },
  {
    id: "ty-komisyon-artisi",
    name: "Trendyol Komisyon +%2",
    icon: "⚠️",
    module: "costImpact",
    description: "Komisyon artışının marjına etkisi",
    inputs: { commissionDelta: 0.02, shippingDelta: 0, costDelta: 0 },
  },
  {
    id: "yeni-urun-lansman",
    name: "Yeni Ürün Lansmanı (%30 marj)",
    icon: "🚀",
    module: "newProductLaunch",
    description: "Yeni ürün için sağlıklı marj ile lansman fiyatı",
    inputs: { targetMargin: 0.30 },
  },
  {
    id: "fiyat-indirim-test",
    name: "Fiyat İndirim Testi (-%10)",
    icon: "📉",
    module: "priceElasticity",
    description: "%10 fiyat indirimiyle talep ne kadar artar?",
    inputs: { priceChange: -0.10, elasticity: -1.5 },
  },
  {
    id: "reklam-budget-2x",
    name: "Reklam Bütçesi 2x",
    icon: "📢",
    module: "adRoas",
    description: "Reklam bütçesini iki katına çıkarmak mantıklı mı?",
    inputs: { budgetMultiplier: 2, decayFactor: 0.7 },
  },
  {
    id: "tedarik-maliyet-emergency",
    name: "Tedarik Krizi (+%15)",
    icon: "💸",
    module: "costImpact",
    description: "Maliyet artışının kâra etkisi",
    inputs: { commissionDelta: 0, shippingDelta: 0, costDelta: 0.15 },
  },
  {
    id: "bundle-vs-discount",
    name: "Bundle vs İndirim",
    icon: "📦",
    module: "campaign",
    description: "3-al-2-öde bundle simülasyonu",
    inputs: { campaignType: "bundle", bundleN: 3, bundleM: 2, demandLift: 0.30 },
  },
  {
    id: "premium-pricing",
    name: "Premium Pricing (%30 marj)",
    icon: "✨",
    module: "reversePricing",
    description: "Yüksek marj hedefiyle premium fiyatlandırma",
    inputs: { targetMargin: 0.30, commission: 0.18, adSpend: 0.05 },
  },
  {
    id: "sicak-rakip-saldiri",
    name: "Sıcak Rakip Saldırısı (-%5 fiyat)",
    icon: "🔥",
    module: "priceElasticity",
    description: "Rakip fiyat düşürdü, biz de düşürelim mi?",
    inputs: { priceChange: -0.05, elasticity: -2.0 },
  },
];
